services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Basilicom\PimcorePluginSystemBanner\EventListener\AdminClassicAssetsListener: ~

    Basilicom\PimcorePluginSystemBanner\EventListener\LoginScreenBannerListener: ~
